spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id:
            client-secret:
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            client-name: Kakao
            scope: profile_nickname, profile_image, account_email
        provider:
          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id

#kakao:
#  url:
#    auth: https://kauth.kakao.com
#    api: https://kapi.kakao.com
#  custom:
#    #    code: http://localhost:8080/login/oauth2/code/kakao
#    code: http://localhost:8080/custom/code
#    token: http://localhost:8080/custom/token
#    user: http://localhost:8080/custom/user

universe:
  token:
    cookieName: jwt
    secret: UniverseUniverseUniverseUniverseUniverseUniverseUniverseUniverseUniverse
    expirationMillis: 864000000

#jwt:
#  secret: universe
#  expiration: 864000000   #Millis