spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id:
            client-secret:
            redirect-uri:
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            client-name: Kakao
            scope: profile_nickname, profile_image, account_email
        provider:
          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id

universe:
  token:
    cookieName: jwt
    secret: universeuniverseuniverseuniverseuniverseuniverse
    expirationMillis: 864000000
